name: konomi
favicon: null
layout_spectrum: 0.10321627533994615
typography_spectrum: 0.22105446876958013
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8620284150820225
  lightness: 0.14076640596613288
  saturation: 0.18128650588914752
  rhythmicContrast: 0.18779347161762416
purpose: []
