name: konomi
favicon: null
layout_spectrum: 0.50974
typography_spectrum: 0.22105446876958013
title: konomi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#204079'
    - '#3360a3'
    - '#b2d3f2'
    - '#447dcc'
    - '#6ca4df'
  brandStrength: 1
  lightness: 0.14076640596613288
  saturation: 0.18128650588914752
  rhythmicContrast: 0.18779347161762416
purpose: []
