name: konomi
favicon: null
layout_spectrum: 0.75463
typography_spectrum: 0.29712
title: konomi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#858585'
    - '#363636'
    - '#c2c2c2'
    - '#e9e9e9'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
