name: konomi
favicon: null
layout_spectrum: 0.50974
typography_spectrum: 0.75649
title: konomi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3eaeb'
    - '#161513'
    - '#364744'
    - '#646a61'
    - '#8d9384'
  brandStrength: 1
  lightness: 0.14076640596613288
  saturation: 0.125
  rhythmicContrast: 0.18779347161762416
purpose: []
