name: konomi
favicon: null
layout_spectrum: 0.25216
typography_spectrum: 0.26299
title: konomi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3eaeb'
    - '#161513'
    - '#364744'
    - '#646a61'
    - '#8d9384'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
